/*  00_setup.sql  –  Foundation tables for Strava Oracle demo
    SQL-only load via External Tables – no Python, no JSON needed.
    Creates : strava_dir     – Oracle directory pointing to CSV files
              strava_ext     – external table over all CSV files
              runs           – 1 row per run   (derived from samples)
              samples        – 1 row per GPS point
*/

-- ============================================================
-- 1. Oracle directory for the CSV files
--    Adjust the path to match your environment.
-- ============================================================
CREATE OR REPLACE DIRECTORY strava_dir AS '/opt/oracle/data';

-- ============================================================
-- 2. External table: reads all CSV files at once
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP TABLE strava_ext_raw'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE strava_ext_raw (
    filename    VARCHAR2(255),
    ts          VARCHAR2(30),
    latitude    VARCHAR2(50),
    longitude   VARCHAR2(50),
    altitude    VARCHAR2(50),
    heart_rate  VARCHAR2(20),
    power       VARCHAR2(20),
    cadence     VARCHAR2(20),
    speed       VARCHAR2(50),
    temperature VARCHAR2(20),
    distance    VARCHAR2(50)
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY strava_dir
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        SKIP 1
        LOAD WHEN (filename != 'filename')
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
    )
    LOCATION ('*.csv')
)
REJECT LIMIT UNLIMITED;

-- View with proper numeric conversion.
-- RTRIM(…, CHR(13)) strips the trailing \r from the last CSV field
-- (Windows CRLF line endings on a Linux container).
CREATE OR REPLACE VIEW strava_ext AS
SELECT
    filename,
    ts,
    TO_NUMBER(latitude,  '999.9999999999999', 'NLS_NUMERIC_CHARACTERS=''.,''') AS latitude,
    TO_NUMBER(longitude, '999.9999999999999', 'NLS_NUMERIC_CHARACTERS=''.,''') AS longitude,
    TO_NUMBER(altitude,  '99999.99',          'NLS_NUMERIC_CHARACTERS=''.,''') AS altitude,
    TO_NUMBER(heart_rate)                                                      AS heart_rate,
    TO_NUMBER(power)                                                           AS power,
    TO_NUMBER(cadence)                                                         AS cadence,
    TO_NUMBER(speed,        '999.999',        'NLS_NUMERIC_CHARACTERS=''.,''') AS speed,
    TO_NUMBER(temperature,  '999.9',          'NLS_NUMERIC_CHARACTERS=''.,''') AS temperature,
    CAST(TO_BINARY_DOUBLE(RTRIM(distance, CHR(13))) AS NUMBER)                  AS distance
FROM strava_ext_raw
WHERE filename != 'filename';

-- Verify the data
SELECT filename, COUNT(*) AS cnt
FROM strava_ext
GROUP BY filename
ORDER BY filename;

-- ============================================================
-- 3. runs  –  one row per activity (derived from external table)
-- ============================================================
DROP TABLE samples CASCADE CONSTRAINTS PURGE; 
DROP TABLE runs CASCADE CONSTRAINTS PURGE;

CREATE TABLE runs (
    run_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                        CONSTRAINT runs_pk PRIMARY KEY,
    filename            VARCHAR2(200) NOT NULL,
    sport               VARCHAR2(50),
    start_time          TIMESTAMP,
    total_elapsed_time  NUMBER,          -- seconds
    total_distance      NUMBER,          -- km
    avg_heart_rate      NUMBER,
    max_heart_rate      NUMBER,
    avg_speed           NUMBER,          -- km/h
    max_speed           NUMBER,          -- km/h
    start_lat           NUMBER,          -- degrees
    start_lon           NUMBER           -- degrees
);

INSERT INTO runs
    (filename, sport, start_time, total_elapsed_time, total_distance,
     avg_heart_rate, max_heart_rate, avg_speed, max_speed,
     start_lat, start_lon)
WITH parsed AS (
    SELECT filename,
           TO_TIMESTAMP(ts, 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"') AS ts_val,
           latitude, longitude, heart_rate, speed, distance
      FROM strava_ext
)
SELECT filename,
       'running',
       MIN(ts_val),
       EXTRACT(DAY    FROM (MAX(ts_val) - MIN(ts_val))) * 86400
     + EXTRACT(HOUR   FROM (MAX(ts_val) - MIN(ts_val))) * 3600
     + EXTRACT(MINUTE FROM (MAX(ts_val) - MIN(ts_val))) * 60
     + EXTRACT(SECOND FROM (MAX(ts_val) - MIN(ts_val))),
       MAX(distance),
       ROUND(AVG(CASE WHEN heart_rate > 0 THEN heart_rate END), 1),
       MAX(heart_rate),
       ROUND(AVG(CASE WHEN speed > 0 THEN speed END), 4),
       MAX(speed),
       MIN(latitude)  KEEP (DENSE_RANK FIRST ORDER BY ts_val),
       MIN(longitude) KEEP (DENSE_RANK FIRST ORDER BY ts_val)
  FROM parsed
 GROUP BY filename
 ORDER BY MIN(ts_val);

COMMIT;

-- ============================================================
-- 4. samples  –  one row per GPS point
-- ============================================================
CREATE TABLE samples (
    sample_id   NUMBER GENERATED ALWAYS AS IDENTITY
                CONSTRAINT samples_pk PRIMARY KEY,
    run_id      NUMBER NOT NULL
                CONSTRAINT samples_run_fk REFERENCES runs(run_id),
    ts          TIMESTAMP       NOT NULL,
    lat         NUMBER,                          -- degrees
    lon         NUMBER,                          -- degrees
    altitude    NUMBER,                          -- metres
    speed       NUMBER,                          -- km/h
    heart_rate  NUMBER,                          -- bpm
    cadence     NUMBER,
    power       NUMBER,                          -- watts
    distance    NUMBER                           -- cumulative km
);

INSERT /*+ APPEND */ INTO samples
    (run_id, ts, lat, lon, altitude, speed, heart_rate, cadence, power, distance)
SELECT r.run_id,
       TO_TIMESTAMP(e.ts, 'YYYY-MM-DD"T"HH24:MI:SS.FF3"Z"'),
       e.latitude,
       e.longitude,
       e.altitude,
       e.speed,
       e.heart_rate,
       e.cadence,
       e.power,
       e.distance
  FROM strava_ext e
  JOIN runs r ON e.filename = r.filename;

COMMIT;

-- ============================================================
-- 5. Constraints & Indexes
-- ============================================================
ALTER TABLE samples ADD CONSTRAINT samples_run_ts_uq
    UNIQUE (run_id, ts);

CREATE INDEX samples_latlon_idx ON samples (lat, lon);

-- ============================================================
-- 6. Quick verification
-- ============================================================
SELECT 'runs'    AS tbl, COUNT(*) AS cnt FROM runs
 UNION ALL
SELECT 'samples',       COUNT(*)         FROM samples;
